language: php

php:
  - 5.6
  - 7.1

services:
  - mysql

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]] ; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update
  - travis_retry mysql -e 'CREATE DATABASE IF NOT EXISTS `t-cms`;'
  - travis_retry npm install -g n
  - travis_retry n stable

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - travis_retry npm install
  - travis_retry cd themes/default; npm install; cd ../../

before_script:
  - cp .env.example .env
  - travis_retry php artisan key:generate
  - travis_retry php artisan vendor:publish
  - travis_retry php artisan migrate --seed
  - travis_retry npm run production
  - travis_retry npm run production --theme:default

script:
  vendor/bin/phpunit